### ISSUE TITLE
SHADER ERROR

### ISSUE THREAD

**Issue by ctal96** [sugi-cho/ProjectionSpray#1]
Shader error in 'Unlit/CanvasObjectVisualizer': failed to open source file: 'Assets/CGINC/ColorCollect.cginc' at line 20 (on d3d11)

Compiling Vertex program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_COLORSPACE_GAMMA UNITY_LIGHT_PROBE_PROXY_VOLUME

**Comment by sugi-cho** [comment]
I forgot to put the "CGINC" folder ;)
and I put it
